variables:
  VERSION: $CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

stages:
  - package
  - build
  - test

Package:
  stage: package
  image: maven:3.8-adoptopenjdk-11
  script:
    - mvn package --no-transfer-progress -Dapp.version=$VERSION -DskipTests=true
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

Image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cp target/*.jar .
    - docker build --build-arg VERSION=$VERSION -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - docker container prune -f
    - docker rmi -f $DOCKER_IMAGE

Test:
  stage: test
  image: maven:3.8-adoptopenjdk-11
  script:
    - mvn verify -Dapp.version=$VERSION --no-transfer-progress
